"""Market Event - Price Updates, Volume, Ticks"""

from dataclasses import dataclass
from decimal import Decimal
from typing import Dict, Optional
from events.event import BaseEvent


@dataclass
class MarketEvent(BaseEvent):
    """
    Market data event containing price, volume, and tick information.
    
    Generated by market data providers when new market data arrives.
    """
    
    symbol: str = ""
    price: Decimal = Decimal("0")
    volume: Decimal = Decimal("0")
    timestamp: Optional[str] = None  # Exchange timestamp if available
    bid: Optional[Decimal] = None
    ask: Optional[Decimal] = None
    open_24h: Optional[Decimal] = None
    high_24h: Optional[Decimal] = None
    low_24h: Optional[Decimal] = None
    volume_24h: Optional[Decimal] = None
    tick_size: Optional[Decimal] = None
    additional_data: Optional[Dict] = None

