"""Order Intent Event - Trading Intent Before Risk Check"""

from dataclasses import dataclass
from decimal import Decimal
from typing import Dict, Optional
from events.event import BaseEvent
# Forward reference to avoid circular import
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from events.signal_event import SignalEvent


@dataclass
class OrderIntentEvent(BaseEvent):
    """
    Order intent before risk check.
    
    Generated by StrategyAllocator when a signal is approved for execution.
    Contains all order details that will be checked by RiskEngine.
    """
    
    symbol: str = ""
    side: str = "Buy"  # "Buy" or "Sell"
    quantity: Decimal = Decimal("0")
    entry_price: Decimal = Decimal("0")
    stop_loss: Decimal = Decimal("0")
    take_profit: Decimal = Decimal("0")
    strategy_name: str = ""
    signal_event_id: Optional[str] = None  # Reference to original SignalEvent
    original_signal: Optional["SignalEvent"] = None  # Reference to original
    order_type: str = "Market"
    time_in_force: str = "GTC"
    metadata: Optional[Dict] = None

