"""Order Submission Event - Order Sent to Exchange"""

from dataclasses import dataclass
from decimal import Decimal
from typing import Dict, Optional
from events.event import BaseEvent


@dataclass
class OrderSubmissionEvent(BaseEvent):
    """
    Order submitted to exchange.
    
    Generated by OrderExecutor when order is sent to exchange.
    Contains exchange order ID and client order ID.
    """
    
    client_order_id: str = ""  # Our UUID for idempotency
    exchange_order_id: Optional[str] = None  # Exchange-assigned ID
    symbol: str = ""
    side: str = ""
    quantity: Decimal = Decimal("0")
    price: Decimal = Decimal("0")
    order_type: str = "Market"
    time_in_force: str = "GTC"
    status: str = "Submitted"  # Submitted, Rejected, Filled, Cancelled
    rejection_reason: Optional[str] = None
    metadata: Optional[Dict] = None

