"""Risk Approval Event - Risk Engine Decision"""

from dataclasses import dataclass
from typing import Dict, Optional
from events.event import BaseEvent
# Forward reference to avoid circular import
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from events.order_intent_event import OrderIntentEvent


@dataclass
class RiskApprovalEvent(BaseEvent):
    """
    Risk engine approval or rejection of an order intent.
    
    Generated by RiskEngine after evaluating OrderIntentEvent.
    """
    
    order_intent_id: str = ""  # Reference to original OrderIntentEvent
    approved: bool = False
    reason: str = ""  # Explanation for approval/rejection
    adjusted_quantity: Optional[float] = None  # Risk engine may adjust size
    adjusted_stop_loss: Optional[float] = None  # Risk engine may adjust SL
    adjusted_take_profit: Optional[float] = None  # Risk engine may adjust TP
    risk_metrics: Optional[Dict] = None  # Risk calculations
    original_intent: Optional["OrderIntentEvent"] = None  # Reference to original

