"""Signal Event - Trading Signals from Strategies"""

from dataclasses import dataclass
from decimal import Decimal
from typing import Dict, Optional
from events.event import BaseEvent


@dataclass
class SignalEvent(BaseEvent):
    """
    Trading signal generated by a strategy.
    
    Contains all information needed to evaluate and potentially execute a trade.
    """
    
    symbol: str = ""
    side: str = "Buy"  # "Buy" or "Sell"
    strategy_name: str = ""
    entry_price: Decimal = Decimal("0")
    stop_loss: Decimal = Decimal("0")
    take_profit: Decimal = Decimal("0")
    confidence: float = 0.0  # 0.0 to 1.0
    quantity: Optional[Decimal] = None  # Optional: strategy can suggest size
    reasoning: Optional[str] = None  # Human-readable explanation
    metadata: Optional[Dict] = None  # Additional strategy-specific data
    time_in_force: str = "GTC"  # GTC, IOC, FOK
    order_type: str = "Market"  # Market, Limit

